hls::vector interface for DuplicateStreams
Xilinx/finn-hlslib pull request #141
Opened 2024-04-24 13:37 UTC by vopade

Changed interfaces of `DuplicateStreams` and `DuplicateStreams_Batch` from packed to hls::vector

2024-05-03 13:55 UTC, preusser requested changes
Thanks for your contribution, @vopade!
Please, review the comments. Mostly, I'd like to ask you to avoid whitespace changes that are a mere consequence of editor settings or personal preference.

2024-05-03 13:55 UTC, preusser commented on streamtools.h
> +  }
Please, undo mere indentation changes.

2024-05-03 13:55 UTC, preusser commented on streamtools.h
> +
Please, remove this extra empty line.

2024-05-03 13:55 UTC, preusser commented on streamtools.h
> +  for (unsigned int image = 0; image < numReps; image++) {
Please, don't just change indentation.

2024-05-03 13:55 UTC, preusser commented on tb/data/dup_stream_config.h
> +constexpr unsigned NUM_REPEAT = 4;
Please, fix missing end of line.

2024-05-03 13:55 UTC, preusser commented on tb/dup_stream_tb.cpp
> +  unsigned int count_out = 0;
Again, many lines are just indentation changes. Please, undo.

2024-05-03 13:55 UTC, preusser commented on tb/dup_stream_top.cpp
>  #include "bnn-library.h"
It looks like you could reduce these includes to `hls_stream.h` only. Please, do if possible.

2024-05-03 13:55 UTC, preusser commented on tb/dup_stream_top.cpp
> +void Testbench_dup_stream(stream<T> & in, stream<T> & out1, stream<T> & out2, unsigned int numReps){
As a consequence of the above, please, use `hls::stream` rather than `stream`.

2024-05-10 13:12 UTC, vopade commented
Hi @preusser,
I made the requested changes, please review again.

2024-05-13 11:54 UTC, preusser commented
THanks, @vopade! This looks good. Getting ready for the merge ...

2024-06-05 14:30 UTC, vopade commented
Commit for pooling operators was automatically added to this PR since it was still open. Please review @preusser

2026-02-25 04:59 UTC, preusser-amd commented
Obsoleted by #169.

2026-02-25 04:59 UTC, closed without merging